name: Pull Request Validation

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  validate-pr:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Aftman
      uses: ok-nick/setup-aftman@v0.4.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Check PR title
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        echo "PR Title: $PR_TITLE"
        
        # Check if PR title follows conventional commits
        if [[ "$PR_TITLE" =~ ^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+ ]]; then
          echo "✅ PR title follows conventional commits format"
        else
          echo "⚠️  PR title should follow conventional commits format"
          echo "Examples: feat: add new feature, fix: resolve bug, docs: update readme"
        fi
        
    - name: Check changed files
      run: |
        echo "📁 Files changed in this PR:"
        git diff --name-only origin/main...HEAD
        
        # Check if any Luau files were changed
        if git diff --name-only origin/main...HEAD | grep -E '\.(lua|luau)$'; then
          echo "🔍 Luau files detected - running additional validation"
        fi
        
    - name: Install dependencies
      run: wally install
      
    - name: Validate build
      run: |
        echo "🔨 Testing build process..."
        rojo sourcemap --output test-sourcemap.json
        echo "✅ Build validation passed"
        
    - name: Comment on PR
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🤖 **Automated PR Validation**\n\n✅ All checks passed! This PR is ready for review.\n\n**What was validated:**\n- Project structure\n- Build process\n- File changes\n\nGreat work! 🎉'
          })